# Generated by Django 4.2.6 on 2023-10-15 19:52

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="student",
            name="department",
            field=models.CharField(
                blank=True,
                help_text="Faculty and department of the student",
                max_length=50,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="student",
            name="level",
            field=models.CharField(
                choices=[
                    ("100L", "100L"),
                    ("200L", "200L"),
                    ("300L", "300L"),
                    ("400L", "400L"),
                    ("500L", "500L"),
                    ("NA", "NA"),
                ],
                default="100L",
                max_length=10,
            ),
        ),
    ]
