# Generated by Django 4.2.6 on 2023-10-15 21:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0003_alter_course_code_alter_course_name_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="staff",
            options={"verbose_name": "staff", "verbose_name_plural": "staff"},
        ),
        migrations.AddField(
            model_name="student",
            name="_user",
            field=models.OneToOneField(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="student",
                related_query_name="student",
                to=settings.AUTH_USER_MODEL,
            ),
            preserve_default=False,
        ),
    ]
