# Generated by Django 4.2.6 on 2023-10-17 10:40

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0004_alter_staff_options_student__user"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="student",
            name="_user",
        ),
        migrations.AddField(
            model_name="student",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="student",
            name="name",
            field=models.CharField(blank=True, max_length=250),
        ),
        migrations.AddField(
            model_name="student",
            name="registration_no",
            field=models.CharField(default="91029102MCA", max_length=20, unique=True),
            preserve_default=False,
        ),
    ]
